### ISSUE TITLE
Doesn't work with gnome-shell 40

### ISSUE THREAD

**Issue by ndias** [askmrsinh/touchpad-indicator#70]
I changed in the metadata the version to 40 and doesn't work

**Comment by edwkmho** [comment]
Dear developer, 

Any chance you will make this work with gnome 40.x. 

Hope to have support soon. Thanks.

**Comment by ashessin** [comment]
There's no support for GNOME 40 at the moment.
The [Settings.ui](https://github.com/ashessin/touchpad-indicator/blob/0ac3bdd843d2a545aeb71968538f2ca4e9888e02/Settings.ui) file is generated through Glade for GTK3 and needs to be ported to GTK4. It's over 1000 lines of code.

**Comment by peter-kehl** [comment]
Summary of the below: It works in GNOME 41.1 except for "Indicator Preferences."

I had this installed on Manjaro for years - thank you. The menu and turning on/off pointer devices continues to work on current Manjaro's GNOME 41.1. Only "Indicator Preferences" fails with:

```
Gtk.BuilderError: /home/pkehl/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/Settings.ui:46:39 Invalid property: GtkBox.margin_left

Stack trace:
  TouchpadIndicatorSettings@/home/pkehl/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/prefs.js:52:23
  buildPrefsWidget@/home/pkehl/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/prefs.js:242:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```
